name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World"
          echo "It is a great day to learn GitHub Actions!"
      - name: Print Goodbye
        run: echo "Goodbye!"
